
name: 自动push脚本

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0 5 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get sitemap
        run: echo Hello, world!

      - name: post to baidu
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
